INSERT INTO activities (project_id, name) VALUES (8, 'est');
INSERT INTO activities (project_id, name) VALUES (10, 'duis');
INSERT INTO activities (project_id, name) VALUES (2, 'at turpis');
INSERT INTO activities (project_id, name) VALUES (9, 'proin');
INSERT INTO activities (project_id, name) VALUES (7, 'at vulputate');
INSERT INTO activities (project_id, name) VALUES (6, 'vestibulum');
INSERT INTO activities (project_id, name) VALUES (9, 'sit amet');
INSERT INTO activities (project_id, name) VALUES (6, 'orci eget');
INSERT INTO activities (project_id, name) VALUES (7, 'posuere metus');
INSERT INTO activities (project_id, name) VALUES (6, 'nec');